# Generated by Django 5.0.3 on 2024-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='description',
            field=models.CharField(default='null', max_length=5000),
            preserve_default=False,
        ),
    ]
