# Generated by Django 5.0.3 on 2024-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_headline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='category',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
